---
version: '3.1'
services:

  shortener:
    image: urlshortener/urlshortener
    build: .
    env_file:
      - .env
    ports:
      - 52520:52520
    restart: unless-stopped

  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: url-shortener-db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    env_file:
      - .env
    volumes:
      - db:/config
      - ./db_init/init.sql:/config/initdb.d/init.sql
    ports:
      - 3306:3306
    restart: unless-stopped


volumes:
  db:
