---
version: '3.1'
services:

  shortener:
    image: urlshortener/urlshortener
    container_name: url-shortener-backend
    build: .
    env_file:
      - .env
    ports:
      - 52520:52520
    depends_on:
      - db
    restart: "no"

  db:
    image: mysql:8.0
    container_name: url-shortener-db
    environment:
      - TIMEZONE=Europe/Budapest
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    restart: "no"


volumes:
  db:
